version: '3.8'

services:
  api:
    build:
      context: .
    ports:
      - "5555:5555"
    environment:
      - MONGO_URI=mongodb://mongo:27017/secantDB
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: secantDB 
    volumes:
      - mongo-data:/data/db
      - ./mongo-seed/:/docker-entrypoint-initdb.d/

volumes:
  mongo-data:


